name: Python CI/CD

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # Add any other project dependencies here if needed
    - name: Run tests and generate report
      run: |
        pytest --junitxml=pytest-report.xml
    - name: Upload pytest report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: pytest-report.xml